### ISSUE TITLE
What is radius? How to tune scale and const?

### ISSUE THREAD

**Issue by Michaelsqj** [seung-lab/kimimaro#53]
Hi! I'm a beginner. 
1. May I ask what does radius in skeleton means? Does it mean the radius at each vertex? And is it in physical unit?
2.  How do tune the scale and const parameters? I mean, is there any standard for reference?

**Comment by william-silversmith** [comment]
Hi Michael,

I'm glad you're finding Kimimaro useful. ^_^

> May I ask what does radius in skeleton means? Does it mean the radius at each vertex? And is it in physical unit?

The radius is the euclidean distance from a vertex to the nearest object boundary in physical distance (that is, with the anisotropy applied). If the vertex is displaced from the center, there are holes in the object, or sharp changes in the object shape it can be shorter than you might expect. I'd regard it as the distance to the boundary is at least this much rather than being exact.

> How do tune the scale and const parameters? I mean, is there any standard for reference?

Fortunately or unfortunately the TEASAR algorithm is manually tunable for handling different levels of detail capture. 

Give these two articles a read and let me know if you have any additional questions:

https://github.com/seung-lab/kimimaro/wiki/A-Pictorial-Guide-to-TEASAR-Skeletonization
https://github.com/seung-lab/kimimaro/wiki/Intuition-for-Setting-Parameters-const-and-scale

Good luck on your skeletonization journey!
Will

**Comment by Michaelsqj** [comment]
Thank you so much for such detailed explanation! Can't be more grateful!

**Comment by william-silversmith** [comment]
Glad I could help. :) Please write in if you have more questions!
