### ISSUE TITLE
skeletontricks.find_target scaling issue

### ISSUE THREAD

**Issue by chinasaur** [seung-lab/kimimaro#64]
Thanks for this very useful package!

We had scaling issues with the raster scan of the whole segment bounding volume in skeleton_tricks.find_target when using 512x512x512 block sizes containing astrocytes that span most of the block and require many skeleton paths. (We don't use any premarked targets, and were using invalidation scale 2.)

This was fairly easy to fix by caching targets in descending distance order and then only scanning the remaining cached target locations on each find_target call. I did this only for segments whose bounding volume was more than 1e6 voxels, but it's probably okay to just do for all cases. I can send you a patch if it's helpful.

**Comment by william-silversmith** [comment]
(black) this change (blue) current master branch

<img width="845" alt="image" src="https://user-images.githubusercontent.com/2517065/131200009-8ffda9d1-2d80-472a-85dc-5d50486f9d6d.png">

**Comment by chinasaur** [comment]
Looks nice; interesting if it's faster overall without switching depending on the bounding volume size. This is a 512^3 test volume? I suspect there's still some advantage to not caching for the smaller bounding volume objects. At least in my tests a single raster scan find_target was much faster than the caching computations for those small ones; I didn't actually benchmark the full skeletonization for them though.

**Comment by william-silversmith** [comment]
Yea, it's the `connectomics.npy` volume in the repository. It's been my standard test volume for years because it has lots of different kinds of objects in it including a glia and a partial soma. 

For very small volumes, the extreme points optimization avoids computing the cache if there's only one target needed, so some of that work is already done. I've not seen a ton of improvement deleting DAF (will have to look more carefully), so if we just keep it around, we could pick regular or cached find_target based on the number of initial foreground voxels. However, I am very encouraged that the average time for the cached `find_target` is only 844.3 µs per hit. It's gonna be hard to beat that. The total time taken by find_target in the second profile was only 1.9 seconds in 97.1 seconds. 

This might be good enough.
